### ISSUE TITLE
Comments, CONTRIBUTING.md, and README.md?

### ISSUE THREAD

**Issue by jamen** [quartz-powered/server#12]
All of the mentioned are important in my opinion.

For anyone wanting to contribute, it's important to set guidelines for them to do so.  That being said, I recommend adding a README.md and CONTRIBUTING.md.  Although comments really are an optional thing, I think they'd be important for a open source project like this one.

**Comment by Emiel45** [comment]
If you'd like to you can make a pr for this, I agree that this is something we require.

**Comment by Emiel45** [comment]
We still need to fill out these files.
