### ISSUE TITLE
@Log

### ISSUE THREAD

**Issue by phase** [quartz-powered/server#27]
Lombok comes with [`@Log`](https://projectlombok.org/features/Log.html) so you don't have to do `@Inject private Logger logger;`. You should be able to use `@Log(topic="logger")` on top of the classes you want loggers for.

**Comment by Emiel45** [comment]
Injecting the logger gives us full (runtime) control over how it's created and works fine the way it works right now. If you're interested in how it works check out: https://github.com/quartz-powered/server/blob/master/src/main/java/org/quartzpowered/common/inject/logger/LoggerMembersInjector.java
